INSERT INTO `CATEGORY` (`ID`, `NAME`) VALUES (1, 'Etel');
INSERT INTO `CATEGORY` (`ID`, `NAME`) VALUES (2, 'Ital');

INSERT INTO `PRODUCT` (`ID`, `NAME`, `PRICE`, `OUT_OF_ORDER`, `DESCRIPTION`, `CATEGORY_ID`) VALUES (1, 'Pizza', 1200, FALSE, 'Finom', 1);
INSERT INTO `PRODUCT` (`ID`, `NAME`, `PRICE`, `OUT_OF_ORDER`, `DESCRIPTION`, `CATEGORY_ID`) VALUES (2, 'Fanta', 150, FALSE, 'Nagyon Finom', 2);
INSERT INTO `PRODUCT` (`ID`, `NAME`, `PRICE`, `OUT_OF_ORDER`, `DESCRIPTION`, `CATEGORY_ID`) VALUES (3, 'Csirek', 800, TRUE, 'Nem Finom', 1);
INSERT INTO `PRODUCT` (`ID`, `NAME`, `PRICE`, `OUT_OF_ORDER`, `DESCRIPTION`, `CATEGORY_ID`) VALUES (4, 'Hambi', 900, FALSE, 'Nagyon nagyon Finom', 1);
INSERT INTO `PRODUCT` (`ID`, `NAME`, `PRICE`, `OUT_OF_ORDER`, `DESCRIPTION`, `CATEGORY_ID`) VALUES (5, 'Cola', 150, FALSE, 'Hidegen Finom', 2);
